=== Conor-Ryan8/XML-Schemas/tennisslams.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.TennisSlams.org"
            xmlns="http://www.TennisSlams.org"
            elementFormDefault="qualified">
  
    <!-- ################### Simple Element Declarations ################### -->   
    <xsd:simpleType name="name">                  
        <xsd:restriction base="xsd:string">                       
            <xsd:enumeration value="Australia"/>
            <xsd:enumeration value="French Open"/> 
            <xsd:enumeration value="Wimbledon"/>   
            <xsd:enumeration value="US Open"/>                  
        </xsd:restriction>                   
    </xsd:simpleType>  
    
    <xsd:simpleType name="winner">                  
        <xsd:restriction base="xsd:string">                       
            <xsd:enumeration value="Djokovic"/>
            <xsd:enumeration value="Nadal"/> 
            <xsd:enumeration value="Federer"/>                
        </xsd:restriction>                   
    </xsd:simpleType> 

    <xsd:simpleType name="runnerUp">                  
        <xsd:restriction base="xsd:string">                       
            <xsd:enumeration value="Tsonga"/>
            <xsd:enumeration value="Federer"/> 
            <xsd:enumeration value="Murray"/>                    
        </xsd:restriction>                   
    </xsd:simpleType>  
    
    <xsd:simpleType name="score"> 
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-6]-[0-4],[0-6]-[0-4],[0-6]-[0-4]"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="surface">                  
        <xsd:restriction base="xsd:string">                       
            <xsd:enumeration value="Rebound Ace"/>
            <xsd:enumeration value="Clay"/> 
            <xsd:enumeration value="Grass"/>   
            <xsd:enumeration value="Hard Court"/>                  
        </xsd:restriction>                   
    </xsd:simpleType>  
    
    <xsd:simpleType name="semiFinalist">                  
        <xsd:restriction base="xsd:string">                       
            <xsd:enumeration value="Nadal"/>
            <xsd:enumeration value="Federer"/> 
            <xsd:enumeration value="Djokovic"/>   
            <xsd:enumeration value="Monfils"/>
            <xsd:enumeration value="Safin"/>
            <xsd:enumeration value="Schuettler"/>                  
        </xsd:restriction>                   
    </xsd:simpleType>  
    
    <!-- ################### Complex Element Declaration ################### -->     
    <xsd:element name="slam">
        <xsd:complexType>           
            <xsd:sequence>
                <xsd:element name="winner" type="winner"/>
                <xsd:element name="runnerUp" type="runnerUp"/>
                <xsd:element name="score" type="score"/>
                <xsd:element name="surface" type="surface"/>
                <xsd:element name="semiFinalist" type="semiFinalist" maxOccurs="2"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="name" />
            <xsd:attribute name="year" type="xsd:gYear" />   
        </xsd:complexType>
    </xsd:element> 
                  
    <!-- ################### Main Element ################### -->                     
    <xsd:element name="slams">
        <xsd:complexType>           
            <xsd:sequence>   
                <xsd:element ref="slam" maxOccurs="4"/>                                           
            </xsd:sequence>         
        </xsd:complexType>
    </xsd:element>        
    
</xsd:schema>

=== Conor-Ryan8/XML-Schemas/tennisslams.xml
<?xml version="1.0"?>
<slams  xmlns="http://www.TennisSlams.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.TennisSlams.org tennisslams.xsd"> 

    <slam name="Australia" year="2008">
        <winner>Djokovic</winner>
        <runnerUp>Tsonga</runnerUp>
        <score>6-2,6-4,6-3</score>
        <surface>Rebound Ace</surface>
        <semiFinalist>Nadal</semiFinalist>
        <semiFinalist>Federer</semiFinalist>
    </slam>
    
    <slam name="French Open" year="2008">
	<winner>Nadal</winner>
	<runnerUp>Federer</runnerUp>
	<score>6-2,6-1,6-0</score>
	<surface>Clay</surface>
	<semiFinalist>Djokovic</semiFinalist>
	<semiFinalist>Monfils</semiFinalist>
    </slam>
        
    <slam name="Wimbledon" year="2008">
	<winner>Nadal</winner>
	<runnerUp>Federer</runnerUp>
	<score>6-4,6-3,6-1</score>
	<surface>Grass</surface>
	<semiFinalist>Safin</semiFinalist>
	<semiFinalist>Schuettler</semiFinalist>
    </slam>
        
    <slam name="US Open" year="2008">
	<winner>Federer</winner>
	<runnerUp>Murray</runnerUp>
	<score>6-3,6-4,6-4</score>
	<surface>Hard Court</surface>
	<semiFinalist>Nadal</semiFinalist>
	<semiFinalist>Djokovic</semiFinalist>
    </slam>
    
</slams>
